sudo: required
services:
  - docker



before_install:
  - docker build -t docker-desktop/docker-react -f Dockerfile.dev .


script:
  - docker run docker-desktop/docker-react npm run test -- --coverage