name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build Docker image
      run: docker build -t docker-react-app -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true docker-react-app npm run test -- --coverage
